#!/usr/bin/env node
/* jshint node: true */
/*
 * Reads an abstract syntax tree from stdin and writes the corresponding
 * scalable vector graphic to stdout
 *
 * ### `ast2svg_source`
 * The only script remaining here. It takes an abstract syntax tree and renders
 * the SVG _without_ embedding the original source in it.
 *
 * ```sh
 *      ./utl/ast2svg < funkysyntaxtree.json > vectorgraphicswithjsonsource.svg
 * ```
 *
 * or in combination with the command line interface:
 * ```sh
 *      node mscgen.js -p -i hello.mscin -o - | ./utl/ast2svg_source > hello_with_json_source.svg
 *  ```
 */

/* jshint unused: true */
var jsdom = require("jsdom");
var renderast = require("../src/script/render/graphics/renderast");

jsdom.env("<html><body></body></html>", function(err, window) {
    var gInput = "";

    process.stdin.resume();
    process.stdin.setEncoding("utf8");

    process.stdin.on("data", function(pChunk) {
        gInput += pChunk;
    });

    process.stdin.on("end", function() {
        var lAST = JSON.parse(gInput);
        renderast.renderAST(lAST, gInput, "__svg", window);
        process.stdout.write(window.document.body.innerHTML);
        process.stdin.pause();
    });

});
/*
 This file is part of mscgen_js.

 mscgen_js is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 mscgen_js is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with mscgen_js.  If not, see <http://www.gnu.org/licenses/>.
 */
